// Generated by CoffeeScript 2.5.0
(function() {
  var DBHandler, DBProxy, MongoDao;

  DBProxy = require("./DBProxy");

  DBHandler = require("./DBHandler");

  //#
  // dao定义.
  //#
  MongoDao = class MongoDao {
    /*
     * 构造函数.
     * @param config 目标数据库的相关配置
     * @param cont 目标库与表
     */
    constructor(config, cont) {
      var col, i, k, len, perfix, postfix, v;
      if (!config) {
        throw "未进行数据库配置";
      }
      if (!cont) {
        throw "请传入实例化库和集合";
      }
      perfix = `mongodb://${config.username}:${config.password}@${config.hostName}:${config.port}/`;
      postfix = `?${config.auth}`;
      for (k in cont) {
        v = cont[k];
        this[k] = {};
        if (!Array.isArray(v)) {
          this[k][v] = new DBProxy(new DBHandler(perfix + k + postfix, v, config.DB_OPTS));
        } else {
          for (i = 0, len = v.length; i < len; i++) {
            col = v[i];
            this[k][col] = new DBProxy(new DBHandler(perfix + k + postfix, col, config.DB_OPTS));
          }
        }
      }
    }

  };

  module.exports = MongoDao;

}).call(this);
